PROBLEMS:
  - belgian_model
  - belgian_model_small
  - microgrid
  - netlib_25fv47
  - netlib_25fv47__eq
  - netlib_25fv47__ineq
  - netlib_80bau3b
  - netlib_80bau3b__ineq
  - netlib_adlittle
  - netlib_adlittle__ineq
  - netlib_agg
  - netlib_agg2
  - netlib_agg2__ineq
  - netlib_agg3
  - netlib_agg3__ineq
  - netlib_agg__ineq
  - netlib_bandm
  - netlib_bandm__eq
  - netlib_beaconfd
  - netlib_beaconfd__eq
  - netlib_beaconfd__ineq
  - netlib_blend
  - netlib_blend__ineq
  - netlib_bnl1
  - netlib_bnl1__eq
  - netlib_bnl1__ineq
  - netlib_bnl2
  - netlib_bnl2__eq
  - netlib_bnl2__ineq
  - netlib_boeing1
  - netlib_boeing1__ineq
  - netlib_boeing2
  - netlib_boeing2__ineq
  - netlib_bore3d
  - netlib_bore3d__eq
  - netlib_brandy
  - netlib_brandy__eq
  - netlib_brandy__ineq
  - netlib_capri__eq
  - netlib_cycle
  - netlib_cycle__eq
  - netlib_czprob
  - netlib_czprob__eq
  - netlib_czprob__ineq
  - netlib_d2q06c
  - netlib_d2q06c__eq
  - netlib_d2q06c__ineq
  - netlib_d6cube
  - netlib_d6cube__eq
  - netlib_degen2
  - netlib_degen2__eq
  - netlib_degen2__ineq
  - netlib_degen3
  - netlib_degen3__eq
  - netlib_degen3__ineq
  - netlib_e226
  - netlib_e226__ineq
  - netlib_etamacro__eq
  - netlib_fffff800
  - netlib_fffff800__eq
  - netlib_fffff800__ineq
  - netlib_finnis__ineq
  - netlib_fit1d
  - netlib_fit1d__ineq
  - netlib_fit1p
  - netlib_fit1p__eq
  - netlib_fit2d
  - netlib_fit2d__ineq
  - netlib_fit2p
  - netlib_fit2p__eq
  - netlib_fit2p__ineq
  - netlib_forplan
  - netlib_forplan__ineq
  - netlib_ganges
  - netlib_ganges__eq
  - netlib_ganges__ineq
  - netlib_gfrd-pnc
  - netlib_gfrd-pnc__eq
  - netlib_gfrd-pnc__ineq
  - netlib_greenbea
  - netlib_greenbea__eq
  - netlib_greenbea__ineq
  - netlib_greenbeb
  - netlib_greenbeb__eq
  - netlib_greenbeb__ineq
  - netlib_grow15
  - netlib_grow15__eq
  - netlib_grow15__ineq
  - netlib_grow22
  - netlib_grow22__eq
  - netlib_grow22__ineq
  - netlib_grow7
  - netlib_grow7__eq
  - netlib_grow7__ineq
  - netlib_israel
  - netlib_israel__ineq
  - netlib_lotfi
  - netlib_lotfi__ineq
  - netlib_maros
  - netlib_maros-r7
  - netlib_maros-r7__eq
  - netlib_maros__eq
  - netlib_maros__ineq
  - netlib_modszk1
  - netlib_modszk1__eq
  - netlib_nesm__eq
  - netlib_perold
  - netlib_perold__eq
  - netlib_perold__ineq
  - netlib_pilot4
  - netlib_pilot4__eq
  - netlib_pilot4__ineq
  - netlib_pilot87__eq
  - netlib_pilot__eq
  - netlib_pilot__ineq
  - netlib_pilotnov
  - netlib_pilotnov__eq
  - netlib_recipe
  - netlib_recipe__ineq
  - netlib_sc105
  - netlib_sc105__ineq
  - netlib_sc205
  - netlib_sc205__ineq
  - netlib_scagr25
  - netlib_scagr25__ineq
  - netlib_scagr7
  - netlib_scagr7__ineq
  - netlib_scfxm1
  - netlib_scfxm1__ineq
  - netlib_scfxm2
  - netlib_scfxm2__ineq
  - netlib_scfxm3
  - netlib_scfxm3__ineq
  - netlib_scorpion
  - netlib_scorpion__ineq
  - netlib_scrs8
  - netlib_scrs8__eq
  - netlib_scrs8__ineq
  - netlib_scsd1
  - netlib_scsd6
  - netlib_scsd6__eq
  - netlib_scsd8
  - netlib_scsd8__eq
  - netlib_sctap1
  - netlib_sctap1__eq
  - netlib_sctap1__ineq
  - netlib_sctap2
  - netlib_sctap2__eq
  - netlib_sctap2__ineq
  - netlib_sctap3
  - netlib_sctap3__eq
  - netlib_sctap3__ineq
  - netlib_seba
  - netlib_seba__eq
  - netlib_seba__ineq
  - netlib_share1b
  - netlib_share1b__ineq
  - netlib_share2b
  - netlib_shell__eq
  - netlib_ship04l
  - netlib_ship04l__eq
  - netlib_ship04l__ineq
  - netlib_ship04s
  - netlib_ship04s__eq
  - netlib_ship04s__ineq
  - netlib_ship08l
  - netlib_ship08l__eq
  - netlib_ship08l__ineq
  - netlib_ship08s
  - netlib_ship08s__eq
  - netlib_ship08s__ineq
  - netlib_ship12l
  - netlib_ship12l__eq
  - netlib_ship12l__ineq
  - netlib_ship12s
  - netlib_ship12s__eq
  - netlib_ship12s__ineq
  - netlib_sierra
  - netlib_sierra__eq
  - netlib_sierra__ineq
  - netlib_standata
  - netlib_standata__eq
  - netlib_standata__ineq
  - netlib_standgub
  - netlib_standgub__eq
  - netlib_standgub__ineq
  - netlib_standmps
  - netlib_standmps__eq
  - netlib_standmps__ineq
  - netlib_stocfor1
  - netlib_stocfor1__ineq
  - netlib_stocfor2
  - netlib_stocfor2__eq
  - netlib_stocfor2__ineq
  - toy_1
  - toy_2
  - toy_3
  - toy_4

NS:
  - 2
  - 6
  - 11

BOUND_TYPES:
  robust_flat: True
  robust_line_left: True
  robust_line_right: True
  robust_xyflat: True
  lagrangian_flat: True
  lagrangian_line: True
  lagrangian_quadratic: True
  robust_concave_envelope: True
  robust_fixed_slope_pairwise: True
  lagrangian_envelope: True


UPPER_BOUNDS_SELECTED:
  - robust_fixed_slope_pairwise
  - robust_xyflat
  - robust_line_right
  - robust_flat

LOWER_BOUNDS_SELECTED:
  - robust_fixed_slope_pairwise
  - robust_xyflat
  - robust_line_right
  - robust_flat
  - lagrangian_flat