LP:
#- belgian_model
#- belgian_model_small
- microgrid
- toy_1
- toy_2
- toy_3
- toy_4
- netlib_beaconfd_eq
- netlib_ship04s_ineq
- netlib_stocfor1_ineq
- netlib_israel_ineq
- netlib_sierra_ineq
- netlib_grow22_eq
- netlib_standgub_eq
- netlib_etamacro_eq
- netlib_sctap3_eq
- netlib_brandy_eq
- netlib_czprob_eq
- netlib_sctap2_eq
- netlib_fit2p_eq
- netlib_ship08l_eq
- netlib_scagr25_ineq
- netlib_ship04s_eq
- netlib_fffff800_eq
- netlib_perold_eq
- netlib_bnl2_eq
- netlib_fit1p_eq
- netlib_ship12s_eq
- netlib_d2q06c_eq
- netlib_fit1d_ineq
- netlib_pilotnov_eq
- netlib_pilot4_eq
- netlib_scrs8_ineq
- netlib_fit2p_ineq
- netlib_bandm_eq
- netlib_fffff800_ineq
- netlib_ship04l_ineq
- netlib_woodw_ineq
- netlib_maros_eq
- netlib_scfxm3_eq
- netlib_gfrd-pnc_eq
- netlib_pilot_ineq
- netlib_sc205_ineq
- netlib_25fv47_ineq
- netlib_bnl1_ineq
- netlib_standgub_ineq
- netlib_stocfor2_eq
- netlib_scfxm1_ineq
- netlib_tuff_ineq
- netlib_seba_eq
- netlib_brandy_ineq
- netlib_lotfi_ineq
- netlib_ganges_eq
- netlib_d6cube_eq
- netlib_tuff_eq
- netlib_gfrd-pnc_ineq
- netlib_fit2d_ineq
- netlib_bore3d_eq
- netlib_sctap1_ineq
- netlib_czprob_ineq
- netlib_greenbeb_eq
- netlib_scfxm2_eq
- netlib_grow15_ineq
- netlib_degen2_eq
- netlib_beaconfd_ineq
- netlib_grow7_ineq
- netlib_sctap2_ineq
- netlib_cycle_ineq
- netlib_ganges_ineq
- netlib_scfxm3_ineq
- netlib_scfxm1_eq
- netlib_shell_eq
- netlib_scsd6_eq
- netlib_grow22_ineq
- netlib_standata_ineq
- netlib_bnl2_ineq
- netlib_scfxm2_ineq
- netlib_ship08l_ineq
- netlib_degen3_eq
- netlib_standata_eq
- netlib_sctap3_ineq
- netlib_recipe_ineq
- netlib_ship12s_ineq
- netlib_pilotnov_ineq
- netlib_agg3_ineq
- netlib_modszk1_eq
- netlib_capri_eq
- netlib_sctap1_eq
- netlib_bore3d_ineq
- netlib_grow7_eq
- netlib_maros_ineq
- netlib_scorpion_ineq
- netlib_d2q06c_ineq
- netlib_ship12l_eq
- netlib_scrs8_eq
- netlib_seba_ineq
- netlib_degen2_ineq
- netlib_bnl1_eq
- netlib_standmps_eq
- netlib_greenbeb_ineq
- netlib_ship04l_eq
- netlib_25fv47_eq
- netlib_woodw_eq
- netlib_ship08s_eq
- netlib_pilot4_ineq
- netlib_agg_ineq
- netlib_grow15_eq
- netlib_d6cube_ineq
- netlib_share1b_ineq
- netlib_perold_ineq
- netlib_cycle_eq
- netlib_blend_ineq
- netlib_pilot_eq
- netlib_degen3_ineq
- netlib_ship12l_ineq
- netlib_scsd8_eq
- netlib_stocfor2_ineq
- netlib_sc105_ineq
- netlib_standmps_ineq
- netlib_ship08s_ineq
- netlib_sierra_eq
- netlib_wood1p_eq

MIP:
- miplib_mzzv11_eq
- miplib_app1-1_eq
- miplib_nu25-pr12_ineq
- miplib_neos-2987310-joes_ineq
- miplib_neos-1582420_ineq
- miplib_sp150x300d_ineq
- miplib_mzzv11_ineq
- miplib_drayage-100-23_eq
- miplib_drayage-100-23_ineq
- miplib_30n20b8_ineq
- miplib_fastxgemm-n2r6s0t2_ineq
- miplib_mzzv42z_ineq
- miplib_mzzv42z_eq
- miplib_neos-1171448_ineq
- miplib_swath1_ineq
- miplib_neos-860300_ineq
- miplib_drayage-25-23_eq
- miplib_mc11_eq
- miplib_drayage-25-23_ineq
- miplib_neos8_ineq
- miplib_nursesched-sprint02_ineq
- miplib_neos-2987310-joes_eq
- miplib_app1-1_ineq
- miplib_neos-3381206-awhea_ineq
- miplib_physiciansched6-2_eq
- miplib_p200x1188c_eq
- miplib_swath1_eq
- miplib_nursesched-sprint02_eq
- miplib_sp150x300d_eq
- miplib_p200x1188c_ineq
- miplib_n5-3_ineq
- facility_p1
- facility_p10
- facility_p11
- facility_p12
- facility_p13
- facility_p14
- facility_p15
- facility_p16
- facility_p17
- facility_p18
- facility_p19
- facility_p2
- facility_p20
- facility_p21
- facility_p22
- facility_p23
- facility_p24
- facility_p25
- facility_p26
- facility_p27
- facility_p28
- facility_p29
- facility_p3
- facility_p30
- facility_p31
- facility_p32
- facility_p33
- facility_p34
- facility_p35
- facility_p36
- facility_p37
- facility_p38
- facility_p39
- facility_p4
- facility_p40
- facility_p41
- facility_p42
- facility_p43
- facility_p44
- facility_p45
- facility_p46
- facility_p47
- facility_p48
- facility_p49
- facility_p5
- facility_p50
- facility_p51
- facility_p52
- facility_p53
- facility_p54
- facility_p55
- facility_p56
- facility_p57
- facility_p58
- facility_p59
- facility_p6
- facility_p60
- facility_p61
- facility_p62
- facility_p63
- facility_p64
- facility_p65
- facility_p66
- facility_p67
- facility_p68
- facility_p69
- facility_p7
- facility_p70
- facility_p71
- facility_p8
- facility_p9
- facility_saiwa
- unit_100_0_1_w
- unit_100_0_2_w
- unit_100_0_3_w
- unit_100_0_4_w
- unit_100_0_5_w
- unit_100_50_1_w
- unit_100_50_2_w
- unit_10_0_1_w
- unit_10_0_2_w
- unit_10_0_3_w
- unit_10_0_4_w
- unit_10_0_5_w
- unit_150_0_1_w
- unit_150_0_2_w
- unit_150_0_3_w
- unit_150_0_4_w
- unit_150_0_5_w
- unit_150_75_1_w
- unit_150_75_2_w
- unit_200_0_10_w
- unit_200_0_11_w
- unit_200_0_12_w
- unit_200_0_1_w
- unit_200_0_2_w
- unit_200_0_3_w
- unit_200_0_4_w
- unit_200_0_5_w
- unit_200_0_6_w
- unit_200_0_7_w
- unit_200_0_8_w
- unit_200_0_9_w
- unit_200_100_1_w
- unit_200_100_2_w
- unit_20_0_1_w
- unit_20_0_2_w
- unit_20_0_3_w
- unit_20_0_4_w
- unit_20_0_5_w
- unit_20_10_1_w
- unit_20_10_2_w
- unit_50_0_1_w
- unit_50_0_2_w
- unit_50_0_3_w
- unit_50_0_4_w
- unit_50_0_5_w
- unit_50_20_1_w
- unit_50_20_2_w
- unit_75_0_1_w
- unit_75_0_2_w
- unit_75_0_3_w
- unit_75_0_4_w
- unit_75_0_5_w
- unit_75_35_1_w
- unit_75_35_2_w

NS:
  - 2
  - 6
  - 11

BOUND_TYPES_LP:
  - robust_flat
  - robust_line_left
  - robust_line_right
  - robust_xyflat
  - lagrangian_flat
  - lagrangian_flat_coef
  - lagrangian_bisegment
  - lagrangian_bisegment_coef
  - robust_concave_envelope
  - robust_fixed_slope_pairwise
  - component_flat

BOUND_TYPES_MIP:
  robust_flat: ["ub"]
  component_flat: ["lb", "ub"]
  lagrangian_flat: ["lb"]
  lagrangian_flat_coef: ["lb"]
  lagrangian_bisegment: ["lb"]
  lagrangian_bisegment_coef: ["lb"]


UPPER_BOUNDS_SELECTED:
  - component_flat

LOWER_BOUNDS_SELECTED:
  - component_flat
